version: "3"
services:
  jenkins-blueocean:
    container_name: jenkins-playground
    build:
      context: .
      dockerfile: Dockerfile

    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
