apiVersion: v1
kind: Pod
metadata:
  name: node.helloworld.com
  labels:
    app: my-helloworld
spec:
  containers:
    - name: k8s-practice
      image: wardviaene/k8s-demo
      ports:
        - name: helloworld-port
          containerPort: 3000
