apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: helloworld-port
    protocol: TCP
  selector:
    app: my-helloworld
  type: NodePort
